services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "2020:2020"
    env_file:
      - local.env
    depends_on:
      - db
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 2020

  db:
    image: postgres:12
    build:
      context: ./backend
      dockerfile: Dockerfile.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - local.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - local.env
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  node_modules:

